name: p4-airflow-python-cassandra

services:
  cassandra:
    image: docker.io/library/cassandra:5.0.9
    container_name: p4-cassandra
    environment:
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
      CASSANDRA_CLUSTER_NAME: p4-cluster
    ports:
      - "14042:9042"
    volumes:
      - p4-cassandra-data:/var/lib/cassandra
    networks:
      - p4-net

  airflow:
    build: ./airflow
    image: localhost/p4-airflow:latest
    container_name: p4-airflow
    environment:
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "True"
      CASSANDRA_HOST: p4-cassandra
      CASSANDRA_PORT: "9042"
      ORDERS_CSV: /opt/airflow/data/orders.csv
    ports:
      - "14081:8080"
    volumes:
      - ./dags:/opt/airflow/dags:Z
      - ./data:/opt/airflow/data:Z
    depends_on:
      - cassandra
    networks:
      - p4-net

  ui:
    build: ./ui
    image: localhost/p4-ui:latest
    container_name: p4-ui
    environment:
      CASSANDRA_HOST: p4-cassandra
      CASSANDRA_PORT: "9042"
      UI_PORT: "8000"
    ports:
      - "14080:8000"
    depends_on:
      - cassandra
    networks:
      - p4-net

volumes:
  p4-cassandra-data:
    name: p4-cassandra-data

networks:
  p4-net:
    name: p4-net
