FROM docker.io/library/python:3.14.7-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY data data
COPY app app
ENV PYTHONUNBUFFERED=1 PYTHONPATH=/app/app
CMD ["python", "app/server.py"]
