gravitino.server.shutdown.timeout = 3000
gravitino.server.webserver.host = 0.0.0.0
gravitino.server.webserver.httpPort = 8090
gravitino.server.webserver.minThreads = 8
gravitino.server.webserver.maxThreads = 50
gravitino.server.webserver.stopTimeout = 30000
gravitino.server.webserver.idleTimeout = 30000
gravitino.server.webserver.threadPoolWorkQueueSize = 100
gravitino.server.webserver.requestHeaderSize = 131072
gravitino.server.webserver.responseHeaderSize = 131072
gravitino.entity.store = relational
gravitino.entity.store.relational = JDBCBackend
gravitino.entity.store.relational.jdbcUrl = jdbc:h2
gravitino.entity.store.relational.jdbcDriver = org.h2.Driver
gravitino.entity.store.relational.jdbcUser = gravitino
gravitino.entity.store.relational.jdbcPassword = gravitino
gravitino.catalog.cache.evictionIntervalMs = 3600000
gravitino.cache.enabled = false
gravitino.cache.maxEntries = 10000
gravitino.cache.expireTimeInMs = 3600000
gravitino.cache.implementation = caffeine
gravitino.authorization.enable = true
gravitino.authorization.serviceAdmins = anonymous
gravitino.lineage.source = http
gravitino.lineage.sinks = log,http
gravitino.lineage.http.sinkClass = org.apache.gravitino.lineage.sink.LineageHttpSink
gravitino.lineage.http.url = http://r6-marquez:5000
gravitino.lineage.http.authType = none
