FROM docker.io/library/python:3.14.7-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONUNBUFFERED=1
COPY app app
COPY tests tests
CMD ["python", "app/server.py"]
